# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kujx1bI2I11VjEHtQxv-TTkYOuaZvZJ2
"""
# utils/config.py

# General
SEED = 42
DEVICE = "cuda"  # will auto-handle later

# Image settings
IMG_SIZE = (224, 224)
NUM_CHANNELS = 3

# Training (placeholders)
BATCH_SIZE = 32
NUM_EPOCHS = 30
LEARNING_RATE = 1e-4

# Model
BACKBONE = "efficientnet_b3"  # or "vit"
NUM_CLASSES_LUNG = 5
NUM_CLASSES_COLON = 9

# Compression flags (for later chapters)
USE_PRUNING = False
USE_QUANTIZATION = False
USE_DISTILLATION = False

