# -*- coding: utf-8 -*-
"""paths.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q0ho_duxan_oysveOr1YKNzkd8frFIHU
"""

from pathlib import Path

# ===============================
# PROJECT ROOT
# ===============================
PROJECT_ROOT = Path("/content/drive/MyDrive/thesis_code")

# ===============================
# ACTUAL DATASETS (IMAGES)
# ===============================
DATASETS_ROOT = PROJECT_ROOT / "datasets"

LC25000_DIR = DATASETS_ROOT / "LC25000"
NCT_CRC_DIR = DATASETS_ROOT / "NCT-CRC-HE-100K"
CRC_VAL_DIR = DATASETS_ROOT / "CRC-VAL-HE-7K"
GLAS_DIR = DATASETS_ROOT / "GlaS"

# ===============================
# OUTPUT DIRECTORIES
# ===============================
RESULTS_DIR = PROJECT_ROOT / "results"
MODELS_DIR = PROJECT_ROOT / "saved_models"
LOGS_DIR = PROJECT_ROOT / "logs"

RESULTS_DIR.mkdir(parents=True, exist_ok=True)
MODELS_DIR.mkdir(parents=True, exist_ok=True)
LOGS_DIR.mkdir(parents=True, exist_ok=True)

